CLASS zcl_bgpf_event_consume DEFINITION
  PUBLIC ABSTRACT FINAL
  FOR EVENTS OF zbgpfr_inventorytp_006.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_bgpf_event_consume IMPLEMENTATION.
ENDCLASS.
